# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
   imageName: 'amara-api-docker'
   buildConfiguration: 'Release'


steps:
 - task: Docker@2
   inputs:
    containerRegistry: 'docker-service-connection'
    repository: 'alvinespinosadev/amara-api-img'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    
#  - task: DotNetCoreCLI@2
#    inputs:
#      command: test
#      projects: ''
#      arguments: '-- configuration $(buildConfiguration)'