# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:

- task: DotNetCoreCLI@2
  displayName: 'Run unit tests'
  inputs:
    command: test
    projects: '**/*Test/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

# - task: UseDotNet@2
#   inputs:
#     version: '8.x'  # Specify the desired version (e.g., 3.1, 5.0, etc.)
#     installationPath: '$(Agent.ToolsDirectory)/dotnet'  # Optional: Set the installation path (default is $(Agent.ToolsDirectory)/dotnet)

- task: DotNetCoreCLI@2
  displayName: 'dotnet publish --configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
  inputs: 
    command: 'publish'
    publishWebProjects: false
    projects: '**/API.csproj'
    arguments: '-- configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish artifacts'